package rw.aauca.fyp.enums;

public enum StudentState {
    REGISTERED,
    CASE_LETTER_SUBMITTED,
    CASE_LETTER_APPROVED,
    PROTOTYPE_REVIEW,
    PROTOTYPE_GRANTED,
    PROPOSAL_UNDER_REVIEW,
    PROPOSAL_ACCEPTED,
    SUPERVISION,
    BOOK_SUBMITTED,
    PRE_DEFENSE,
    DEFENSE,
    COMPLETED,
    WITHDRAWN
}
